name: ci

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  demo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
      - name: Whoami
        run: aws sts get-caller-identity
      - name: Print the demo parameter
        run: |
          aws ssm get-parameters \
            --names ${{ vars.SSM_DEMO_PARAMETER }} \
            --with-decryption
